import Header from '@/components/Header/Header';
import AuthModal from '@/components/Modals/AuthModal/AuthModal';
import Notes from '@/components/Notes/Notes';
import Head from 'next/head';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mx-auto max-w-screen-lg px-2.5 md:px-5">
        <main>
          <Notes />
        </main>
      </div>
      <AuthModal />
    </>
  );
};
export default HomePage;
