import Footer from '@/components/Footer';
import Header from '@/components/Header/Header';
import AuthModal from '@/components/Modals/AuthModal/AuthModal';
import Notes from '@/components/Notes/Notes';
import Head from 'next/head';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-full flex-col items-center">
        <Header />
        <div className="flex w-full max-w-screen-lg flex-grow flex-col py-7.5 px-2.5 md:px-5">
          <main className="flex-grow">
            <Notes />
          </main>
          <Footer />
        </div>
        <AuthModal />
      </div>
    </>
  );
};
export default HomePage;
